export {Slide} from "./Slider"
export {TheTeam} from "./theTeam"
export {Sponsors} from "./Sponsors"
export {NavBar} from "./NavBar"
export {Eventos} from "./eventos"
export {Mission} from "./mission"
export {Home} from "./Home"